# Generated by Django 2.1.3 on 2019-01-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('unit', models.CharField(max_length=200)),
                ('item_rate_inv', models.DecimalField(decimal_places=10, max_digits=19)),
                ('currency', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('fob_inr', models.DecimalField(decimal_places=10, max_digits=19)),
                ('item_rate_inr', models.DecimalField(decimal_places=10, max_digits=19)),
                ('fob_usd', models.DecimalField(decimal_places=10, max_digits=19)),
                ('foreign_port', models.CharField(max_length=200)),
                ('foreign_country', models.CharField(max_length=200)),
                ('india_port', models.CharField(max_length=200)),
                ('india_company', models.CharField(max_length=200)),
                ('foreign_company', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=200)),
                ('hs_code', models.CharField(max_length=200)),
            ],
        ),
    ]
